import type { Node, Edge } from '@xyflow/react';

export const nodes: Node[] = [
  {
    id: 'canon',
    type: 'nodeCard',
    position: { x: 250, y: 0 },
    data: {
      title: 'Product Canon',
      content: 'Repositório vivo de conhecimento',
      variant: 'canon',
      icon: '📚',
      tooltip: 'Repositório central versionado com regras, vocabulário, processos e decisões técnicas do produto.',
    },
  },
  {
    id: 'build',
    type: 'nodeCard',
    position: { x: 0, y: 200 },
    data: {
      title: 'Etapa 1 — Construir',
      content: '3 sessões formais com aprovação',
      variant: 'default',
      icon: '🔨',
      tooltip: '3 sessões guiadas por IA: Descoberta de Processos, Constituição Técnica e Especificação de Requisitos.',
    },
  },
  {
    id: 'continuity',
    type: 'nodeCard',
    position: { x: 0, y: 380 },
    data: {
      title: 'Decisão de Continuidade',
      content: ['a) Mais fluxos → Discovery', 'b) Mais requisitos → Specification', 'c) Encerrar → Etapa 2'],
      variant: 'decision',
      icon: '🔀',
      tooltip: 'Ao final do Canon Building, o Domain Builder decide: mapear mais fluxos, formalizar mais requisitos ou encerrar o ciclo e prosseguir para Spec Crafting.',
    },
  },
  {
    id: 'use',
    type: 'nodeCard',
    position: { x: 250, y: 530 },
    data: {
      title: 'Etapa 2 — Usar para Especificar',
      content: 'Contexto injetado automaticamente',
      variant: 'default',
      icon: '📝',
      tooltip: 'A IA carrega contexto relevante da Product Canon e confronta a spec com o conhecimento existente.',
    },
  },
  {
    id: 'feedback',
    type: 'nodeCard',
    position: { x: 500, y: 200 },
    data: {
      title: 'Etapa 3 — Devolver o Aprendizado',
      content: 'Retroalimentação formal',
      variant: 'default',
      icon: '🔄',
      tooltip: 'Termos novos, regras descobertas, eventos e decisões técnicas voltam para a Product Canon.',
    },
  },
  {
    id: 'direct-edit',
    type: 'nodeCard',
    position: { x: 500, y: 420 },
    data: {
      title: 'Edição Direta',
      content: ['Canal complementar', 'Domain Expert + IA', 'expert-edit-plan'],
      variant: 'complementary',
      icon: '✏️',
      tooltip: 'O Domain Expert pode editar diretamente artefatos da camada de negócio fora das cerimônias formais. Gera um expert-edit-plan com aprovação obrigatória do Architect.',
    },
  },
];

export const edges: Edge[] = [
  {
    id: 'canon-build',
    source: 'canon',
    target: 'build',
    label: 'contexto injetado',
    animated: true,
    type: 'smoothstep',
    labelStyle: { fill: '#94a3b8', fontSize: 11 },
    style: { stroke: 'rgba(34, 211, 238, 0.5)', strokeWidth: 2 },
  },
  {
    id: 'build-continuity',
    source: 'build',
    target: 'continuity',
    type: 'smoothstep',
    style: { stroke: 'rgba(34, 211, 238, 0.5)', strokeWidth: 2 },
  },
  {
    id: 'continuity-build',
    source: 'continuity',
    target: 'build',
    label: 'mais fluxos / requisitos',
    type: 'smoothstep',
    animated: true,
    labelStyle: { fill: '#a78bfa', fontSize: 10 },
    style: { stroke: 'rgba(167, 139, 250, 0.5)', strokeWidth: 2 },
  },
  {
    id: 'continuity-use',
    source: 'continuity',
    target: 'use',
    label: 'encerrar ciclo',
    type: 'smoothstep',
    labelStyle: { fill: '#a78bfa', fontSize: 10 },
    style: { stroke: 'rgba(167, 139, 250, 0.5)', strokeWidth: 2 },
  },
  {
    id: 'use-feedback',
    source: 'use',
    target: 'feedback',
    type: 'smoothstep',
    style: { stroke: 'rgba(34, 211, 238, 0.5)', strokeWidth: 2 },
  },
  {
    id: 'feedback-canon',
    source: 'feedback',
    target: 'canon',
    label: 'descobertas',
    animated: true,
    type: 'smoothstep',
    labelStyle: { fill: '#94a3b8', fontSize: 11 },
    style: { stroke: 'rgba(34, 211, 238, 0.5)', strokeWidth: 2 },
  },
  {
    id: 'direct-edit-canon',
    source: 'direct-edit',
    target: 'canon',
    label: 'expert-edit-plan',
    type: 'smoothstep',
    animated: true,
    labelStyle: { fill: '#f472b6', fontSize: 10 },
    style: { stroke: 'rgba(244, 114, 182, 0.5)', strokeWidth: 2, strokeDasharray: '6 3' },
  },
];
